---
basePackages:
  - base
  - base-devel
  - btrfs-progs
  - linux
  - linux-headers
  - linux-firmware
  - mkinitcpio
  - cryptsetup
  - device-mapper
  - diffutils
  - dosfstools
  - e2fsprogs
  - efibootmgr
  - exfatprogs
  - f2fs-tools
  - grub
  - inetutils
  - iptables-nft
  - jfsutils
  - less
  - lsb-release
  - lvm2
  - man-db
  - man-pages
  - mdadm
  - networkmanager
  - os-prober
  - perl
  - python
  - s-nail
  - sudo
  - sysfsutils
  - texinfo
  - usbutils
  - which
  - xfsprogs
  - core-skel-kde
  - core-wallpapers
  - core-icons

postInstallFiles:
  - "/etc/default/grub"
  - "/etc/pacman.conf"
  - "/etc/mkinitcpio.conf"
